<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Attivo',
    'Are you sure you want to delete this user?' => 'Sei sicuro di voler cancellare questo utente?',
    'Banned' => 'Bannato',
    'Bind to IP' => 'Restringere all\'IP',
    'Browser' => 'Browser',
    'Change own password' => 'Cambia la propria password',
    'Change password' => 'Cambia la password',
    'Changing password' => 'Cambio password',
    'Changing password for user: ' => 'Cambio password per l\'utente: ',
    'Child permissions' => 'Permessi figli',
    'Child roles' => 'Ruoli figli',
    'Code' => 'Codice',
    'Confirmation Token' => 'Token di conferma',
    'Create' => 'Crea',
    'Created' => 'Creato',
    'Creating permission group' => 'Creazione del gruppo dei permessi',
    'Current password' => 'Password attuale',
    'Data' => 'Dati',
    'Delete' => 'Cancella',
    'Description' => 'Descrizione',
    'E-mail' => 'Email',
    'E-mail confirmed' => 'Email confermato',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'Il link per l\'attivazione è stato inviato a <b>{email}></b>. La scadenza del link è di {minutes} minuti.',
    'Edit' => 'Modifica',
    'Editing' => 'Modifica',
    'Editing permission group' => 'Modifica del gruppo dei permessi',
    'Editing permission: ' => 'Modifica del permesso: ',
    'Editing role: ' => 'Modifica del ruolo: ',
    'Editing user: ' => 'Modifica dell\'utente: ',
    'For example: 123.34.56.78, 168.111.192.12' => 'Per esempio: 123.34.56.78, 168.111.192.12',
    'Group' => 'Gruppo',
    'ID' => 'ID',
    'Inactive' => 'Inattivo',
    'IP' => 'IP',
    'Language' => 'Lingua',
    'Login' => 'Login',
    'Name' => 'Nome',
    'OS' => 'SO',
    'Password' => 'Password',
    'Password has been changed' => 'La password fu cambiata',
    'Permission creation' => 'Permesso creato',
    'Permission groups' => 'Gruppi dei permessi',
    'Permissions' => 'Permessi',
    'Permissions for role:' => 'Permessi per ruolo:',
    'Refresh routes' => 'Ricarica i percorsi',
    'Refresh routes (and delete unused)' => 'Ricarica i percorsi (e cancella quelli non utilizzati)',
    'Registration IP' => 'IP utilizzato durante la registrazione',
    'Repeat password' => 'Ripeti la password',
    'Reset' => 'Reimposta',
    'Role creation' => 'Creazione ruolo',
    'Roles' => 'Ruoli',
    'Roles and permissions' => 'Ruoli e permessi',
    'Roles and permissions for user:' => 'Ruoli e permessi per l\'utente:',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => 'Percorsi che non esistono in questa applicazione verranno cancellati. Non consigliato per gli applicativi con struttura complessa perche la parte amministrativa e la parte dell\'utente finale hanno percorsi diversi',
    'Rule' => 'Regola',
    'Save' => 'Salva',
    'Saved' => 'Salvato',
    'Search' => 'Cerca',
    'Search route' => 'Cerca il percorso',
    'Settings for permission' => 'Impostazioni per il permesso',
    'Show all' => 'Mostra tutti',
    'Show only selected' => 'Mostra solo selezionati',
    'Status' => 'Stato',
    'Superadmin' => 'Superutente',
    'Token' => 'Token',
    'Too many attempts' => 'Troppi tentativi',
    'Type' => 'Tipo',
    'Updated' => 'Aggiornato',
    'User' => 'Utente',
    'User agent' => 'User agent',
    'User creation' => 'Creazione utente',
    'Users' => 'Utenti',
    'Visit Time' => 'L\'ora della visita',
    'Visit log' => 'Lo storico delle visite',
    'Wrong format. Enter valid IPs separated by comma' => 'Formato errato. Inserisci l\'elenco dei IP divisi dalla virgola',
    'Wrong password' => 'Password sbagliata',
    'You can not change own permissions' => 'Non puoi modificare i propri permessi',
];
