<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Active' => 'Attivo',
	'Are you sure you want to delete this user?' => 'Sei sicuro di voler cancellare questo utente?',
	'Banned' => 'Bannato',
	'Bind to IP' => 'Associato a un IP',
	'Browser' => 'Browser',
	'Change own password' => 'Cambia la tua password',
	'Change password' => 'Cambia la password',
	'Changing password for user:' => 'Modifica della password per l\'utente:',
	'Changing password' => 'Modifica della password',
	'Child permissions' => 'Permessi figli',
	'Child roles' => 'Ruoli figli',
	'Code' => 'Codice',
	'Confirmation Token' => 'Token di conferma',
	'Create' => 'Creare',
	'Created' => 'Creato',
	'Creating permission group' => 'Creazione del gruppo di autorizzazioni',
	'Current password' => 'Password attuale',
	'Data' => 'Dati',
	'Delete' => 'Elimina',
	'Description' => 'Descrizione',
	'E-mail confirmed' => 'E-mail confermata',
	'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'L\'e-mail con il link di attivazione è stata inviata a <b> {email} </ b>. Questo link scadrà tra {minutes} min.',
	'E-mail' => 'E-mail',
	'Edit' => 'Modifica',
	'Editing permission group' => 'Modifica del gruppo di autorizzazioni',
	'Editing permission:' => 'Modifica del permesso:',
	'Editing role:' => 'Modifica del ruolo:',
	'Editing user:' => 'Modifica dell\'utente:',
	'Editing' => 'Modifica',
	'For example: 123.34.56.78, 168.111.192.12' => 'Ad esempio: 123.34.56.78, 168.111.192.12',
	'Group' => 'Gruppo',
	'ID' => 'ID',
	'Inactive' => 'Non attivo',
	'IP' => 'IP',
	'Language' => 'Lingua',
	'Login' => 'Login',
	'Name' => 'Nome',
	'OS' => 'OS',
	'Password has been changed' => 'La password è stata cambiata',
	'Password' => 'Password',
	'Permission creation' => 'Creazione del permesso',
	'Permission groups' => 'Gruppi di autorizzazione',
	'Permissions for role:' => 'Autorizzazioni per il ruolo:',
	'Permissions' => 'permessi',
	'Refresh routes (and delete unused)' => 'Aggiorna percorsi (ed elimina quelli non utilizzati)',
	'Refresh routes' => 'Aggiorna percorsi',
	'Registration IP' => 'IP di registrazione',
	'Repeat password' => 'Ripeti la password',
	'Reset' => 'Reset',
	'Role creation' => 'Creazione del ruolo',
	'Roles and permissions for user:' => 'Ruoli e permessi per l\'utente:',
	'Roles and permissions' => 'Ruoli e permessi',
	'Roles' => 'Ruoli',
	'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => 'I percorsi che non sono presenti in questa applicazione saranno cancellati. Non consigliato per applicazioni con struttura "avanzata", perché frontend e backend hanno il proprio set di percorsi.',
	'Rule' => 'Regola',
	'Save' => 'Salvare',
	'Saved' => 'Salvato',
	'Search route' => 'Cerca percorso',
	'Search' => 'Ricerca',
	'Settings for permission' => 'Impostazioni per il permesso',
	'Show all' => 'Mostra tutto',
	'Show only selected' => 'Mostra solo i selezionati',
	'Status' => 'Stato',
	'Superadmin' => 'Superadmin',
	'Token' => 'Token',
	'Too many attempts' => 'Troppi tentativi',
	'Type' => 'Tipo',
	'Updated' => 'Aggiornato',
	'User agent' => 'User agent',
	'User creation' => 'Creazione dell\'utente',
	'User' => 'Utente',
	'Users' => 'Utenti',
	'Visit log' => 'Log delle visite',
	'Visit Time' => 'Ora della visita',
	'Wrong format. Enter valid IPs separated by comma' => 'Formato errato. Inserisci IP validi separati da virgola',
	'Wrong password' => 'Password errata',
	'You can not change own permissions' => 'Non è possibile modificare le proprie autorizzazioni',
];