<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Authorization' => 'Autorizzazione',
	'Captcha' => 'Captcha',
	'Check your E-mail for further instructions' => 'Controlla la tua email per ulteriori istruzioni',
	'Check your e-mail {email} for instructions to activate account' => 'Controlla la tua e-mail {email} per le istruzioni per attivare l\'account',
	'Confirm E-mail' => 'Conferma email',
	'Confirm' => 'Confermare',
	'Continue' => 'Continua',
	'Could not send confirmation email' => 'Impossibile inviare e-mail di conferma',
	'E-mail confirmation for' => 'E-mail di conferma per',
	'E-mail confirmed' => 'E-mail confermata',
	'E-mail is invalid' => 'L\'email non è valida',
	'E-mail' => 'E-mail',
	'Forgot password ?' => 'Ha dimenticato la password ?',
	'Incorrect username or password.' => 'Nome utente o password errati.',
	'Login has been taken' => 'Il login è stato preso',
	'Login' => 'Accesso',
	'Password recovery' => 'Recupero della password',
	'Password reset for' => 'Ripristino password per',
	'Password' => 'Parola d\'ordine',
	'Recover' => 'Recuperare',
	'Register' => 'Registrare',
	'Registration - confirm your e-mail' => 'Registrazione - conferma la tua e-mail',
	'Registration' => 'Registrazione',
	'Remember me' => 'Ricordati di me',
	'Repeat password' => 'ripeti la password',
	'This E-mail already exists' => 'Questa email esiste già',
	'Token not found. It may be expired' => 'Token non trovato. Potrebbe essere scaduto',
	'Token not found. It may be expired. Try reset password once more' => 'Token non trovato. Potrebbe essere scaduto. Prova a reimpostare la password ancora una volta',
	'Too many attempts' => 'Troppi tentativi',
	'Unable to send message for email provided' => 'Impossibile inviare un messaggio per l\'email fornita',
	'Username' => 'Nome utente',
	'You could not login from this IP' => 'Non è possibile accedere da questo IP',
];
