<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail' => 'Email',
    'Username' => 'Nome utente',
    'Authorization' => 'Autorizzazione',
    'Captcha' => 'Captcha',
    'Check your E-mail for further instructions' => 'Controlla la propria email per ulteriori istruzioni',
    'Check your e-mail {email} for instructions to activate account' => 'Controlla la propria email {email} per attivare l\'account',
    'Confirm' => 'Conferma',
    'Confirm E-mail' => 'Conferma l\'email',
    'Continue' => 'Continua',
    'Could not send confirmation email' => 'L\'invio della mail per la conferma non riuscito',
    'E-mail confirmation for' => 'Conferma email per',
    'E-mail confirmed' => 'Email confermato',
    'E-mail is invalid' => 'L\' email non e valido',
    'Forgot password ?' => 'Password dimenticata?',
    'Incorrect username or password.' => 'Nome utente o password sbagliati',
    'Login' => 'Login',
    'Login has been taken' => 'Nome utente già in uso',
    'Password' => 'Password',
    'Password recovery' => 'Recupero password',
    'Password reset for' => 'Cambio password per',
    'Recover' => 'Recupera',
    'Register' => 'Registra',
    'Registration' => 'Registrazione',
    'Registration - confirm your e-mail' => 'Registrazione - conferma la propria email',
    'Remember me' => 'Ricordami',
    'Repeat password' => 'Ripetti la password',
    'This E-mail already exists' => 'Questo email risulta già registrato',
    'Token not found. It may be expired' => 'Token non trovato. Potrebbe essere scaduto',
    'Token not found. It may be expired. Try reset password once more' => 'Token non trovato. Potrebbe essere scaduto. Prova a reimpostare la password di nuovo',
    'Too many attempts' => 'Troppi tentativi',
    'Unable to send message for email provided' => 'L\'invio della mail all\'indirizzo fornito non riuscito',
    'You could not login from this IP' => 'Non puoi loggarti da questo IP',
];
