<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активен',
    'Are you sure you want to delete this user?' => 'Вы уверены, что хотите удалить этого пользователя ?',
    'Banned' => '',
    'Bind to IP' => 'Привязать к IP',
    'Browser' => 'Браузер',
    'Change own password' => 'Смена пароля',
    'Change password' => 'Сменить пароль',
    'Changing password' => 'Смена пароля',
    'Changing password for user: ' => 'Сменя пароля для пользователя: ',
    'Child permissions' => 'Дочерние права',
    'Child roles' => 'Дочерние роли',
    'Code' => 'Код',
    'Confirmation Token' => '',
    'Create' => 'Создать',
    'Created' => 'Создано',
    'Creating permission group' => 'Создание группы прав',
    'Current password' => 'Текущий пароль',
    'Data' => 'Данные',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'E-mail' => '',
    'E-mail confirmed' => 'E-mail подтверждён',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'Ссылка активации была отправлена на <b>{email}></b>. Срок действия ссылки {minutes} мин.',
    'Edit' => 'Редактировать',
    'Editing' => 'Редактирование',
    'Editing permission group' => 'Редактирование группы прав',
    'Editing permission: ' => 'Редактирование права: ',
    'Editing role: ' => 'Редактирование роли: ',
    'Editing user: ' => 'Редактирование пользователя: ',
    'For example: 123.34.56.78, 168.111.192.12' => 'Напрмиер: 123.34.56.78, 168.111.192.12',
    'Group' => 'Группа',
    'ID' => '',
    'Inactive' => 'Неактивен',
    'IP' => '',
    'Language' => 'Язык',
    'Login' => 'Логин',
    'Name' => 'Название',
    'OS' => 'ОС',
    'Password' => 'Пароль',
    'Password has been changed' => 'Пароль был изменён',
    'Permission creation' => 'Создание права',
    'Permission groups' => 'Группы прав',
    'Permissions' => 'Права',
    'Permissions for role:' => 'Права для роли:',
    'Refresh routes' => '',
    'Refresh routes (and delete unused)' => '',
    'Registration IP' => 'IP регистрации',
    'Repeat password' => 'Повторите пароль',
    'Reset' => 'Сбросить',
    'Role creation' => 'Создание роли',
    'Roles' => 'Роли',
    'Roles and permissions' => 'Роли и права',
    'Roles and permissions for user:' => 'Роли и права для пользователя',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => '',
    'Rule' => 'Правило',
    'Save' => 'Сохранить',
    'Saved' => 'Сохранено',
    'Search' => 'Поиск',
    'Search route' => '',
    'Settings for permission' => 'Настройки для права',
    'Show all' => '',
    'Show only selected' => '',
    'Status' => 'Статус',
    'Superadmin' => 'Суперадмин',
    'Token' => '',
    'Too many attempts' => 'Лимит попыток превышен',
    'Type' => 'Тип',
    'Updated' => 'Обновлено',
    'User' => 'Пользователь',
    'User agent' => 'User agent',
    'User creation' => 'Создание пользователя',
    'Users' => 'Пользователи',
    'Visit Time' => 'Время посещения',
    'Visit log' => 'История посещений',
    'Wrong format. Enter valid IPs separated by comma' => 'Неверный формат. Введите список IP разделённых запятой',
    'Wrong password' => 'Неверный пароль',
    'You can not change own permissions' => 'Вы не можете менять свои права',
];
