<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Code' => 'Код',
    'Creating permission group' => 'Создание группы прав',
    'Editing permission group' => 'Редактирование группы прав',
    'Group' => 'Группа',
    'Permission groups' => 'Группы прав',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Active' => 'Активен',
    'Are you sure you want to delete this user?' => 'Вы уверены, что хотите удалить этого пользователя ?',
    'Browser' => 'Браузер',
    'Change own password' => 'Смена пароля',
    'Change password' => 'Сменить пароль',
    'Changing password' => 'Смена пароля',
    'Changing password for user: ' => 'Сменя пароля для пользователя: ',
    'Child permissions' => 'Дочерние права',
    'Child roles' => 'Дочерние роли',
    'Create' => 'Создать',
    'Created' => 'Создано',
    'Current password' => 'Текущий пароль',
    'Data' => 'Данные',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Edit' => 'Редактировать',
    'Editing' => 'Редактирование',
    'Editing permission: ' => 'Редактирование права: ',
    'Editing role: ' => 'Редактирование роли: ',
    'Editing user: ' => 'Редактирование пользователя: ',
    'Inactive' => 'Неактивен',
    'Language' => 'Язык',
    'Login' => 'Логин',
    'Name' => 'Название',
    'OS' => 'ОС',
    'Password' => 'Пароль',
    'Password has been changed' => 'Пароль был изменён',
    'Permission creation' => 'Создание права',
    'Permissions' => 'Права',
    'Permissions for role - "{role}"' => 'Права для роли - "{role}"',
    'Permissions for role:' => 'Права для роли:',
    'Repeat password' => 'Повторите пароль',
    'Role creation' => 'Создание роли',
    'Roles' => 'Роли',
    'Roles and permissions' => 'Роли и права',
    'Roles and permissions for user:' => 'Роли и права для пользователя',
    'Rule' => 'Правило',
    'Save' => 'Сохранить',
    'Settings for permission:' => 'Настройки для права',
    'Status' => 'Статус',
    'Superadmin' => 'Суперадмин',
    'Type' => 'Тип',
    'Updated' => 'Обновлено',
    'User' => 'Пользователь',
    'User agent' => 'User agent',
    'User creation' => 'Создание пользователя',
    'Users' => 'Пользователи',
    'Visit Time' => 'Время посещения',
    'Visit log' => 'История посещений',
    'Wrong format. Enter valid IPs separated by comma' => 'Неверный формат. Введите список IP разделённых запятой',
    'Wrong password' => 'Неверный пароль',
];
