<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail' => '',
    'Username' => 'Логин',
    'Authorization' => 'Авторизация',
    'Captcha' => 'Каптча',
    'Check your E-mail for further instructions' => 'Проверьте Ваш E-mail для дальнейших инструкций',
    'Check your e-mail {email} for instructions to activate account' => 'Проверьте Ваш e-mail {email} для активации аккаунта',
    'Confirm' => 'Подтвердить',
    'Confirm E-mail' => 'Подтвердить E-mail',
    'Continue' => 'Продолжить',
    'Could not send confirmation email' => 'Не удалось отправить e-mail для активации аккаунта',
    'E-mail confirmation for' => 'Подтверждение E-mail для',
    'E-mail confirmed' => 'E-mail подтверждён',
    'E-mail is invalid' => 'Неверный E-mail',
    'Forgot password ?' => 'Забыли пароль ?',
    'Incorrect username or password.' => 'Неверный логин или пароль',
    'Login' => 'Логин',
    'Login has been taken' => 'Логин уже занят',
    'Password' => 'Пароль',
    'Password recovery' => 'Восстановление пароля',
    'Password reset for' => 'Смена пароля для',
    'Recover' => 'Восстановить',
    'Register' => 'Регистрация',
    'Registration' => 'Регистрация',
    'Registration - confirm your e-mail' => 'Регистрация - подтверждение аккаунта',
    'Remember me' => 'Запомнить меня',
    'Repeat password' => 'Повторите пароль',
    'This E-mail already exists' => 'Такой E-mail уже существыет',
    'Token not found. It may be expired' => 'Токен не найден или устарел',
    'Token not found. It may be expired. Try reset password once more' => 'Токен не найдет. Возможно его срок действия истёк. Попробуйте сбросить пароль ещё раз',
    'Too many attempts' => 'Лимит попыток превышен',
    'Unable to send message for email provided' => 'Не удалось отправить письмо на указанный email',
    'You could not login from this IP' => 'Вы не можете входить с этого IP',
];
