<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Captcha' => 'Каптча',
    'E-mail is invalid' => 'Неверный E-mail',
    'Login has been taken' => 'Логин уже занят',
    'Repeat password' => 'Повторите пароль',
    'This E-mail already exists' => '',
    'Too many attempts' => 'Лимит попыток превышен',
    'Authorization' => 'Авторизация',
    'Check your E-mail for further instructions' => 'Проверьте Ваш E-mail для дальнейших инструкций',
    'Forgot password ?' => 'Забыли пароль ?',
    'Incorrect username or password.' => 'Неверный логин или пароль',
    'Login' => 'Логин',
    'Password' => 'Пароль',
    'Password recovery' => 'Восстановление пароля',
    'Recover' => 'Восстановить',
    'Register' => 'Регистрация',
    'Registration' => 'Регистрация',
    'Remember me' => 'Запомнить меня',
    'You could not login from this IP' => 'Вы не можете входить с этого IP',
];
