<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Username' => 'Nombre de usuario',
    'Authorization' => 'Autorización',
    'Captcha' => 'Código Captcha',
    'Check your E-mail for further instructions' => 'Verifique su correo electrónico para más instrucciones',
    'Check your e-mail {email} for instructions to activate account' => 'Verifique su correo electrónico {email} para obtener las instrucciones para activar la cuenta',
    'Confirm' => 'Confirmar',
    'Confirm E-mail' => 'Confirmar correo electrónico',
    'Continue' => 'Continuar',
    'Could not send confirmation email' => 'No fue posible enviar el correo electrónico de confirmación',
    'E-mail' => 'Correo electrónico',
    'E-mail confirmation for' => 'Confirmación del correo electrónico de',
    'E-mail confirmed' => 'Correo electrónico confirmado',
    'E-mail is invalid' => 'Correo electrónico no válido',
    'Forgot password ?' => '¿Olvidó la contraseña?',
    'Incorrect username or password.' => 'Nombre de usuario o contraseña incorrecta.',
    'Login' => 'Iniciar sesión',
    'Login has been taken' => 'Este usuario ya existe',
    'Password' => 'Contraseña',
    'Password recovery' => 'Recuperación de la contraseña',
    'Password reset for' => 'Restablecer la contraseña de',
    'Recover' => 'Recuperar',
    'Register' => 'Registrar',
    'Registration' => 'Registro',
    'Registration - confirm your e-mail' => 'Registro - Confirme su correo electrónico',
    'Remember me' => 'Recordarme',
    'Repeat password' => 'Repita la contraseña',
    'This E-mail already exists' => 'Este correo electrónico ya existe',
    'Token not found. It may be expired' => 'Token no encontrado. Puede haber expirado',
    'Token not found. It may be expired. Try reset password once more' => 'Token no encontrado. Puede haber expirado. Trate de restablecer la contraseña una vez más',
    'Too many attempts' => 'Demasiados intentos',
    'Unable to send message for email provided' => 'No fue posible enviar mensaje al correo electrónico indicado',
    'You could not login from this IP' => 'No pudo iniciar sesión desde esta dirección IP',
];
