<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Actif',
    'Are you sure you want to delete this user?' => 'Etes-vous sûre de vouloir supprimer cet utilisateur ?',
    'Banned' => 'Banni',
    'Bind to IP' => 'Associer à l\'IP',
    'Browser' => 'Navigateur',
    'Change own password' => 'Changer son propre mot de passe',
    'Change password' => 'Changer mot de passe',
    'Changing password' => 'Changement de mot de passe',
    'Changing password for user: ' => 'Changement de mot de passe pour',
    'Child permissions' => 'Sous-permissions ',
    'Child roles' => 'Sous-rôles',
    'Code' => 'Code',
    'Confirmation Token' => 'Jeton de confirmation',
    'Create' => 'Créer',
    'Created' => 'Créé le',
    'Creating permission group' => 'Création de groupe de permission ',
    'Current password' => 'Mot de passe courant',
    'Data' => 'Données',
    'Delete' => 'Supprimer',
    'Description' => 'Description',
    'E-mail' => 'Email',
    'E-mail confirmed' => 'Confirmation d\'email',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'Un email comportant un lien d\'activation a été envoyé à <b>{email}</b>. Ce lien expirera dans {minutes} min.',
    'Edit' => 'Modifier',
    'Editing' => 'Modification',
    'Editing permission group' => 'Modification groupe de permission',
    'Editing permission: ' => 'Modification permission',
    'Editing role: ' => 'Modification rôle',
    'Editing user: ' => 'Modification utilisateur',
    'For example: 123.34.56.78, 168.111.192.12' => 'Par exemple: 123.34.56.78, 168.111.192.12',
    'Group' => 'Groupe',
    'ID' => 'ID',
    'Inactive' => 'Inactif',
    'IP' => 'Adresse IP',
    'Language' => 'Langage',
    'Login' => 'Se connecter',
    'Name' => 'Nom',
    'OS' => 'OS',
    'Password' => 'Mot de passe',
    'Password has been changed' => 'Le mot de passe a été changé',
    'Permission creation' => 'Création de permission',
    'Permission groups' => 'Groupes de permission',
    'Permissions' => 'Permissions',
    'Permissions for role:' => 'Permission pour le rôle:',
    'Refresh routes' => 'Raffraichir les routes',
    'Refresh routes (and delete unused)' => 'Raffraichir les routes (et supprimer les inutilisées)',
    'Registration IP' => 'Adresse IP d\'enregistrement',
    'Repeat password' => 'Répétez le mot de passe',
    'Reset' => 'Remise à zéro',
    'Role creation' => 'Création de rôle',
    'Roles' => 'Rôles',
    'Roles and permissions' => 'Rôles et permissions',
    'Roles and permissions for user:' => 'Rôles et permissions pour l\'utilisateur:',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => '',
    'Rule' => 'Rêgle',
    'Save' => 'Enregistrer',
    'Saved' => 'Enregistrement',
    'Search' => 'Rechercher',
    'Search route' => 'Rechercher une route',
    'Settings for permission' => 'Réglages pour permission',
    'Show all' => 'Afficher tout',
    'Show only selected' => 'Afficher les sélectionnées uniquement',
    'Status' => 'Statut',
    'Superadmin' => 'Superadmin',
    'Token' => 'Jeton',
    'Too many attempts' => 'Trop de tentatives',
    'Type' => 'Type',
    'Updated' => 'Modifié le',
    'User' => 'Utilisateur',
    'User agent' => 'User agent',
    'User creation' => 'Création d\'utilisateur',
    'Users' => 'Utilisateurs',
    'Visit Time' => 'Date de visite',
    'Visit log' => 'Journal des visites',
    'Wrong format. Enter valid IPs separated by comma' => 'Mauvais format. Entrez des adresses IP valides séparées par une virgule',
    'Wrong password' => 'Mauvais mot de passe',
    'You can not change own permissions' => 'Vous ne pouvez pas changer vos propre permissions',
];
