<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail' => 'Email',
    'Username' => 'Nom d\'utilisateur',
    'Authorization' => 'Autorisation',
    'Captcha' => 'Captcha',
    'Check your E-mail for further instructions' => 'Vérifiez vos emails pour de plus amples informations',
    'Check your e-mail {email} for instructions to activate account' => 'Vérifiez vos emails (à {email}) et suivez les instructions afin d\' activer votre compte',
    'Confirm' => 'Confirmer',
    'Confirm E-mail' => 'Confirmation d\'email',
    'Continue' => 'Continuer',
    'Could not send confirmation email' => 'Impossible d\'envoyer la confirmation d\'email',
    'E-mail confirmation for' => 'Confirmation d\'email pour',
    'E-mail confirmed' => 'Email confirmé',
    'E-mail is invalid' => 'L\'adresse email est invalide',
    'Forgot password ?' => 'Mot de passe perdu ?',
    'Incorrect username or password.' => 'Identifiant ou mot de passe incorrect',
    'Login' => 'Se connecter',
    'Login has been taken' => 'L\'identifiant à été pris',
    'Password' => 'Mot de passe',
    'Password recovery' => 'Récupération de mot de passe',
    'Password reset for' => 'Régénération de mot de passe pour',
    'Recover' => 'Récupérer',
    'Register' => 'S\'enregistrer',
    'Registration' => 'Enregistrement',
    'Registration - confirm your e-mail' => 'Enregistrement - confirmer votre email',
    'Remember me' => 'Se rappeller de moi',
    'Repeat password' => 'Répétez le mot de passe',
    'This E-mail already exists' => 'Cet email existe déjà',
    'Token not found. It may be expired' => 'Jeton introuvable, il a peut-être expiré',
    'Token not found. It may be expired. Try reset password once more' => 'Jeton introuvable, il a peut-être expiré. Essayez de regénérer le mot de passe une nouvelle fois',
    'Too many attempts' => 'Trop de tentatives',
    'Unable to send message for email provided' => 'Impossible d\'envoyer le message pour l\'email fournit',
    'You could not login from this IP' => 'Vous ne pouvez pas vous identifier à partir de cette adresse IP',
];
