<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Are you sure you want to delete this user?' => '',
    'Banned' => '',
    'Bind to IP' => '',
    'Browser' => '',
    'Change own password' => '',
    'Change password' => '',
    'Changing password' => '',
    'Changing password for user: ' => '',
    'Child permissions' => '',
    'Child roles' => '',
    'Code' => '',
    'Confirmation Token' => '',
    'Create' => '',
    'Created' => '',
    'Creating permission group' => '',
    'Current password' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'E-mail' => '',
    'E-mail confirmed' => '',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => '',
    'Edit' => '',
    'Editing' => '',
    'Editing permission group' => '',
    'Editing permission: ' => '',
    'Editing role: ' => '',
    'Editing user: ' => '',
    'For example: 123.34.56.78, 168.111.192.12' => '',
    'Group' => '',
    'ID' => '',
    'Inactive' => '',
    'IP' => '',
    'Language' => '',
    'Login' => '',
    'Name' => '',
    'OS' => '',
    'Password' => '',
    'Password has been changed' => '',
    'Permission creation' => '',
    'Permission groups' => '',
    'Permissions' => '',
    'Permissions for role:' => '',
    'Refresh routes' => '',
    'Refresh routes (and delete unused)' => '',
    'Registration IP' => '',
    'Repeat password' => '',
    'Reset' => '',
    'Role creation' => '',
    'Roles' => '',
    'Roles and permissions' => '',
    'Roles and permissions for user:' => '',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => '',
    'Rule' => '',
    'Save' => '',
    'Saved' => '',
    'Search' => '',
    'Search route' => '',
    'Settings for permission' => '',
    'Show all' => '',
    'Show only selected' => '',
    'Status' => '',
    'Superadmin' => '',
    'Token' => '',
    'Too many attempts' => '',
    'Type' => '',
    'Updated' => '',
    'User' => '',
    'User agent' => '',
    'User creation' => '',
    'Users' => '',
    'Visit Time' => '',
    'Visit log' => '',
    'Wrong format. Enter valid IPs separated by comma' => '',
    'Wrong password' => '',
    'You can not change own permissions' => '',
];
