<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authorization' => '',
    'Captcha' => '',
    'Check your E-mail for further instructions' => '',
    'Check your e-mail {email} for instructions to activate account' => '',
    'Confirm' => '',
    'Confirm E-mail' => '',
    'Continue' => '',
    'Could not send confirmation email' => '',
    'E-mail' => '',
    'E-mail confirmation for' => '',
    'E-mail confirmed' => '',
    'E-mail is invalid' => '',
    'Forgot password ?' => '',
    'Incorrect username or password.' => '',
    'Login' => '',
    'Login has been taken' => '',
    'Password' => '',
    'Password recovery' => '',
    'Password reset for' => '',
    'Recover' => '',
    'Register' => '',
    'Registration' => '',
    'Registration - confirm your e-mail' => '',
    'Remember me' => '',
    'Repeat password' => '',
    'This E-mail already exists' => '',
    'Token not found. It may be expired' => '',
    'Token not found. It may be expired. Try reset password once more' => '',
    'Too many attempts' => '',
    'Unable to send message for email provided' => '',
    'Username' => '',
    'You could not login from this IP' => '',
];
