<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktiv',
    'Are you sure you want to delete this user?' => 'Wollen Sie diesen Benutzer wirklich löschen?',
    'Banned' => '',
    'Bind to IP' => 'An IP binden',
    'Browser' => '',
    'Change own password' => 'Eigenes Passwort ändern',
    'Change password' => 'Passwort ändern',
    'Changing password' => 'Ändere Passwort',
    'Changing password for user: ' => 'Ändere Passwort von Benutzer: ',
    'Child permissions' => 'Kind-Berechtigungen',
    'Child roles' => 'Kind-Rollen',
    'Code' => '',
    'Confirmation Token' => '',
    'Create' => 'Erstellen',
    'Created' => 'Erstellt',
    'Creating permission group' => 'Erstelle Berechtigungs-Gruppe',
    'Current password' => 'Aktuelles Passwort',
    'Data' => 'Daten',
    'Delete' => 'Löschen',
    'Description' => 'Beschreibung',
    'E-mail' => '',
    'E-mail confirmed' => 'E-Mail bestätigt',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => '',
    'Edit' => 'Bearbeiten',
    'Editing' => 'Bearbeite',
    'Editing permission group' => 'Bearbeite Berechtigungs-Gruppe',
    'Editing permission: ' => 'Bearbeite Berechtigung',
    'Editing role: ' => 'Bearbeite Rolle',
    'Editing user: ' => 'Bearbeite Benutzer',
    'For example: 123.34.56.78, 168.111.192.12' => 'Zum Beispiel: 123.34.56.78, 168.111.192.12',
    'Group' => 'Gruppe',
    'ID' => '',
    'Inactive' => 'Inaktiv',
    'IP' => '',
    'Language' => 'Sprache',
    'Login' => '',
    'Name' => '',
    'OS' => 'Betriebssystem',
    'Password' => 'Passwort',
    'Password has been changed' => 'Passwort wurde geändert',
    'Permission creation' => 'Berechtigungserstellung',
    'Permission groups' => 'Berechtigungs-Gruppen',
    'Permissions' => 'Berechtigungen',
    'Permissions for role:' => 'Berechtigungen für Rolle',
    'Refresh routes' => '',
    'Refresh routes (and delete unused)' => '',
    'Registration IP' => 'Registrierung IP',
    'Repeat password' => 'Passwort wiederholen',
    'Reset' => 'Zurücksetzen',
    'Role creation' => 'Rollenerstellung',
    'Roles' => 'Rollen',
    'Roles and permissions' => 'Rollen und Berechtigungen',
    'Roles and permissions for user:' => 'Rollen und Berechtigungen von Benutzer:',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => '',
    'Rule' => 'Rolle',
    'Save' => 'Speichern',
    'Saved' => 'Gespeichert',
    'Search' => 'Suchen',
    'Search route' => '',
    'Settings for permission' => 'Einstellungen für Berechtigung',
    'Show all' => '',
    'Show only selected' => '',
    'Status' => '',
    'Superadmin' => 'Super-Administrator',
    'Token' => '',
    'Too many attempts' => 'Zu viele Versuche',
    'Type' => 'Typ',
    'Updated' => 'Aktualisiert',
    'User' => 'Benutzer',
    'User agent' => 'User Agent',
    'User creation' => 'Benutzererstellung',
    'Users' => 'Benutzer',
    'Visit Time' => 'Besucher Zeit',
    'Visit log' => 'Besucher Log',
    'Wrong format. Enter valid IPs separated by comma' => 'Falsches Format. Gültige IP-Adressen komma-getrennt eingeben',
    'Wrong password' => 'Falsches Passwort',
    'You can not change own permissions' => 'Sie können Ihre eigenen Berechtigungen nicht ändern',
];
