<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Captcha' => '',
    'E-mail' => '',
    'Login' => '',
    'Username' => '',
    'Authorization' => 'Autorisierung',
    'Check your E-mail for further instructions' => 'Überprüfen Sie Ihre E-Mail-Adresse für weitere Anweisungen',
    'Check your e-mail {email} for instructions to activate account' => 'Überprüfen Sie Ihre E-Mail-Adresse {email} für weitere Anweisungen zur Kontoaktivierung',
    'Confirm' => 'Bestätigen',
    'Confirm E-mail' => 'E-Mail bestätigen',
    'Continue' => 'Fortsetzen',
    'Could not send confirmation email' => 'E-Mail zur Kontoaktivierung konnte nicht versandt werden',
    'E-mail confirmation for' => 'E-Mail-Bestätigung für',
    'E-mail confirmed' => 'E-Mail bestätigt',
    'E-mail is invalid' => 'E-Mail ist ungültig',
    'Forgot password ?' => 'Passwort vergessen?',
    'Incorrect username or password.' => 'Falscher Benutzername oder Passwort.',
    'Login has been taken' => 'Dieser Login existiert bereits',
    'Password' => 'Passwort',
    'Password recovery' => 'Passwort wiederherstellen',
    'Password reset for' => 'Passwort zurücksetzen für',
    'Recover' => 'Wiederherstellen',
    'Register' => 'Registrieren',
    'Registration' => 'Registrierung',
    'Registration - confirm your e-mail' => 'Registrierung - bestätigen Sie Ihre E-Mail-Adresse',
    'Remember me' => 'Login merken',
    'Repeat password' => 'Passwort wiederholen',
    'This E-mail already exists' => 'Diese E-Mail existiert bereits',
    'Token not found. It may be expired' => 'Token nicht gefunden. Es könnte abgelaufen sein',
    'Token not found. It may be expired. Try reset password once more' => 'Token nicht gefunden. Es könnte abgelaufen sein. Versuchen Sie noch einmal, das Passwort zurückzusetzen',
    'Too many attempts' => 'Zu viele Versuche',
    'Unable to send message for email provided' => 'Es war nicht möglich, die Nachricht an die angegebene E-Mail-Adresse zu senden',
    'You could not login from this IP' => 'Sie können sich von dieser IP nicht anmelden',
];
