<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Are you sure you want to delete this user?' => '',
    'Browser' => '',
    'Change own password' => '',
    'Change password' => '',
    'Changing password' => '',
    'Changing password for user: ' => '',
    'Child permissions' => '',
    'Child roles' => '',
    'Create' => '',
    'Created' => '',
    'Current password' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'Edit' => '',
    'Editing' => '',
    'Editing permission: ' => '',
    'Editing role: ' => '',
    'Editing user: ' => '',
    'Inactive' => '',
    'Language' => '',
    'Login' => '',
    'Name' => '',
    'OS' => '',
    'Password' => '',
    'Password has been changed' => '',
    'Permission creation' => '',
    'Permissions' => '',
    'Permissions for role - "{role}"' => '',
    'Permissions for role:' => '',
    'Repeat password' => '',
    'Role creation' => '',
    'Roles' => '',
    'Roles and permissions' => '',
    'Roles and permissions for user:' => '',
    'Rule' => '',
    'Save' => '',
    'Settings for permission:' => '',
    'Status' => '',
    'Superadmin' => '',
    'Type' => '',
    'Updated' => '',
    'User' => '',
    'User agent' => '',
    'User creation' => '',
    'Users' => '',
    'Visit Time' => '',
    'Visit log' => '',
    'Wrong format. Enter valid IPs separated by comma' => '',
    'Wrong password' => '',
    'Browser And Os' => '@@@@',
    'Permissions for user: ' => '@@@@',
];
