<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Ativo',
    'Are you sure you want to delete this user?' => 'Você tem certeza de que deseja excluir este utilizador?',
    'Banned' => '',
    'Bind to IP' => 'Víncular ao IP',
    'Browser' => 'Navegador',
    'Change own password' => 'Alterar a própria senha',
    'Change password' => 'Alterar senha',
    'Changing password' => 'Alterando a senha',
    'Changing password for user: ' => 'Alterando a senha do utilizador: ',
    'Child permissions' => 'Permissões filhas',
    'Child roles' => 'Regras filhas',
    'Code' => 'Código',
    'Confirmation Token' => '',
    'Create' => 'Criar',
    'Created' => 'Criado',
    'Creating permission group' => 'Criando grupo de permissões',
    'Current password' => 'Senha atual',
    'Data' => 'Dados',
    'Delete' => 'Excluir',
    'Description' => 'Descrição',
    'E-mail' => '',
    'E-mail confirmed' => 'E-mail confirmado',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' =>'Um e-mail com o link de ativação foi enviado para <b>{email}</b>. Este link irá expirar dentro de {minutes} minutos.',
    'Edit' => 'Editar',
    'Editing' => 'Editando',
    'Editing permission group' => 'Editando grupo de permissões',
    'Editing permission: ' => 'Editando permissão: ',
    'Editing role: ' => 'Editando função: ',
    'Editing user: ' => 'Editando utilizador: ',
    'For example: 123.34.56.78, 168.111.192.12' => 'Por exemplo: 123.34.56.78, 168.111.192.12',
    'Group' => 'Grupo',
    'ID' => '',
    'Inactive' => 'Inativo',
    'IP' => '',
    'Language' => 'Idioma',
    'Login' => 'Nome de utilizador',
    'Name' => 'Nome',
    'OS' => 'SO',
    'Password' => 'Senha',
    'Password has been changed' => 'A senha foi alterada',
    'Permission creation' => 'Criação de permissão',
    'Permission groups' => 'Grupos de permissão',
    'Permissions' => 'Permissões',
    'Permissions for role:' => 'Permissões da função:',
    'Refresh routes' => '',
    'Refresh routes (and delete unused)' => '',
    'Registration IP' => 'Registo do IP',
    'Repeat password' => 'Repetir senha',
    'Reset' => 'Redefinir',
    'Role creation' => 'Criação de função',
    'Roles' => 'Funções',
    'Roles and permissions' => 'Funções e permissões',
    'Roles and permissions for user:' => 'Funções e permissões do utilizador:',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => '',
    'Rule' => 'Regra',
    'Save' => 'Salvar',
    'Saved' => 'Salvo',
    'Search' => 'Buscar',
    'Search route' => '',
    'Settings for permission' => 'Configurações de permissões',
    'Show all' => '',
    'Show only selected' => '',
    'Status' => 'Estado',
    'Superadmin' => 'Superadmin',
    'Token' => '',
    'Too many attempts' => 'Demasiadas tentativas',
    'Type' => 'Tipo',
    'Updated' => 'Atualizado',
    'User' => 'Utilizador',
    'User agent' => 'Agente do utilizador',
    'User creation' => 'Criação do utilizador',
    'Users' => 'Utilizadores',
    'Visit Time' => 'Tempo de Visita',
    'Visit log' => 'Registo de Visitas',
    'Wrong format. Enter valid IPs separated by comma' => 'Formato incorreto. Insira endereços de IPs válidos e separados por vírgula',
    'Wrong password' => 'Senha incorreta',
    'You can not change own permissions' => 'Não pode alterar as suas próprias permissões',
];
