<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Captcha' => '',
    'Continue' => '',
    'E-mail' => '',
    'Authorization' => 'Autorização',
    'Check your E-mail for further instructions' => 'Verifique o seu e-mail para mais instruções',
    'Check your e-mail {email} for instructions to activate account' => 'Verifique o seu e-mail {email} para obter instruções para ativar a conta',
    'Confirm' => 'Confirmar',
    'Confirm E-mail' => 'Confirmar E-mail',
    'Could not send confirmation email' => 'Não foi possível enviar email de confirmação',
    'E-mail confirmation for' => 'Confirmação de e-mail para',
    'E-mail confirmed' => 'E-mail confirmado',
    'E-mail is invalid' => 'E-mail inválido',
    'Forgot password ?' => 'Esqueceu-se da senha?',
    'Incorrect username or password.' => 'Nome de utilizador ou senha incorreta.',
    'Login' => 'Entrar',
    'Login has been taken' => 'Este nome de utilizador já existe',
    'Password' => 'Senha',
    'Password recovery' => 'Recuperação de senha',
    'Password reset for' => 'Redefinição de senha para',
    'Recover' => 'Recuperar',
    'Register' => 'Registar',
    'Registration' => 'Registo',
    'Registration - confirm your e-mail' => 'Registo - Confirme o seu e-mail',
    'Remember me' => 'Lembrar',
    'Repeat password' => 'Repita a senha',
    'This E-mail already exists' => 'Este E-mail já existe',
    'Token not found. It may be expired' => 'Token não encontrado. Pode ter sido expirado',
    'Token not found. It may be expired. Try reset password once more' => 'Token não encontrado. Pode ter sido expirado. Tente redefinir a senha mais uma vez',
    'Too many attempts' => 'Demasiadas tentativas',
    'Unable to send message for email provided' => 'Não foi possível enviar mensagem para o e-mail indicado',
    'Username' => 'Nome de Utilizador',
    'You could not login from this IP' => 'Não é possível autenticar-se a partir deste endereço de IP',
];
