<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktywny',
    'Are you sure you want to delete this user?' => 'Czy na pewno chcesz usunąć tego użytkownika?',
    'Bind to IP' => 'Przypisz do IP',
    'Browser' => 'Przeglądarka',
    'Change own password' => 'Zmień swoje hasło',
    'Change password' => 'Zmień hasło',
    'Changing password' => 'Zmiana hasła',
    'Changing password for user: ' => 'Zmiana hasła użytkownika: ',
    'Child permissions' => 'Podrzędne uprawnienia',
    'Child roles' => 'Podrzędne role',
    'Code' => 'Kod',
    'Create' => 'Utwórz',
    'Created' => 'Utworzone',
    'Creating permission group' => 'Tworzenie grupy uprawnień',
    'Current password' => 'Aktualne hasło',
    'Data' => 'Dane',
    'Delete' => 'Usuń',
    'Description' => 'Opis',
    'E-mail confirmed' => 'E-mail potwierdzony',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => '',
    'Edit' => 'Edytuj',
    'Editing' => 'Edytowanie',
    'Editing permission group' => 'Edytowanie grupy uprawnień: ',
    'Editing permission: ' => 'Edytowanie uprawnień: ',
    'Editing role: ' => 'Edytowanie roli: ',
    'Editing user: ' => 'Edycja użytkownika: ',
    'For example: 123.34.56.78, 168.111.192.12' => 'Przykładowo: 123.34.56.78, 168.111.192.12',
    'Group' => 'Grupa',
    'Inactive' => 'Nieaktywny',
    'Banned' => 'Zbanowany',
    'Language' => 'Język',
    'Login' => 'Login',
    'Name' => 'Nazwa',
    'OS' => 'System',
    'Password' => 'Hasło',
    'Password has been changed' => 'Hasło zostało zmienione',
    'Permission creation' => '',
    'Permission groups' => 'Grupy uprawnień',
    'Permissions' => 'Uprawnienia',
    'Permissions for role - "{role}"' => 'Uprawnienia roli - "{role}"',
    'Permissions for role:' => 'Uprawnienia roli: ',
    'Registration IP' => 'Adres IP rejestracji',
    'Repeat password' => 'Powtórz hasło',
    'Reset' => 'Resetuj',
    'Role creation' => 'Tworzenie roli',
    'Roles' => 'Role',
    'Roles and permissions' => 'Role i uprawnienia',
    'Roles and permissions for user:' => 'Role i uprawnienia użytkownika: ',
    'Rule' => 'Reguła',
    'Save' => 'Zapisz',
    'Saved' => 'Zapisano',
    'Search' => 'Szukaj',
    'Settings for permission' => 'Ustawienia uprawnień',
    'Status' => '',
    'Superadmin' => 'Superadministrator',
    'Too many attempts' => 'Zbyt wiele prób',
    'Type' => 'Typ',
    'Updated' => 'Zaktualizowano',
    'User' => 'Użytkownik',
    'User agent' => '',
    'User creation' => 'Dodawanie użytkownika',
    'Users' => 'Użytkownicy',
    'Visit Time' => 'Ostatnia wizyta',
    'Visit log' => 'Rejestr wizyt',
    'Wrong format. Enter valid IPs separated by comma' => 'Nieprawidłowy format. Wpisz prawidłowe adresy IP oddzielone przecinkami',
    'Wrong password' => 'Nieprawidłowe hasło',
    'You can not change own permissions' => 'Nie możesz zmieniać własnych uprawnień',
];
