<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Continue' => 'Kontyntynuj',
    'E-mail' => '',
    'Username' => 'Nazwa użytkownika',
    'Authorization' => 'Logowanie',
    'Captcha' => 'Kod wizualny',
    'Check your E-mail for further instructions' => 'Sprawdź swoją skrzynkę e-mail, gdzie zostały wysłane dalsze instrukcje',
    'Check your e-mail {email} for instructions to activate account' => 'Sprawdź swoją skrzynkę e-mail {email}, gdzie została wysłana instrukcja jak aktywować konto',
    'Confirm' => 'Potwierdź',
    'Confirm E-mail' => 'Potwierdź adres e-mail',
    'Could not send confirmation email' => 'Nie udało się wysłać maila potwierdzającego',
    'E-mail confirmation for' => 'Potwierdzenie e-maila dla',
    'E-mail confirmed' => 'Adres e-mail potwierdzony',
    'E-mail is invalid' => 'Nieprawidłowy adres e-mail',
    'Forgot password ?' => 'Zapomniałeś hasło?',
    'Incorrect username or password.' => 'Nieprawidłowy login lub hasło',
    'Login' => 'Zaloguj',
    'Login has been taken' => 'Login jest już zajęty',
    'Password' => 'Hasło',
    'Password recovery' => 'Odzyskiwanie hasła',
    'Password reset for' => 'Resetowanie hasła dla',
    'Recover' => 'Odzyskaj',
    'Register' => 'Zarejestruj',
    'Registration' => 'Rejestracja',
    'Registration - confirm your e-mail' => 'Rejestracja - potwierdź swój adres e-mail',
    'Remember me' => 'Zapamiętaj mnie',
    'Repeat password' => 'Powtórz hasło',
    'This E-mail already exists' => 'Ten e-mail już istnieje w bazie',
    'Token not found. It may be expired' => 'Klucz nie znaleziony. Mógł skończyć się jego okres ważności.',
    'Token not found. It may be expired. Try reset password once more' => 'Klucz nie znaleziony. Mógł skończyć się jego okres ważności. Spróbuj ponownie zresetować hasło.',
    'Too many attempts' => 'Zbyt wiele prób',
    'Unable to send message for email provided' => 'Nie udało się wysłać wiadomości na podany adres e-mail',
    'You could not login from this IP' => 'Nie możesz się zalogować z tego IP',
];
