<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '활성',
    'Are you sure you want to delete this user?' => '이 사용자를 삭제하시겠습니까?',
    'Banned' => '',
    'Bind to IP' => '아이피에 바인드',
    'Browser' => '브라우져',
    'Change own password' => '자신의 암호를 변경',
    'Change password' => '암호를 변경',
    'Changing password' => '암호를 변경중',
    'Changing password for user: ' => '해당 유저의 암호를 변경중: ',
    'Child permissions' => '자식 권한',
    'Child roles' => '자식 역할',
    'Code' => '코드',
    'Confirmation Token' => '',
    'Create' => '생성',
    'Created' => '성됨',
    'Creating permission group' => '권한 그룹 생성중',
    'Current password' => '현재 암호',
    'Data' => '데이터',
    'Delete' => '삭제',
    'Description' => '설명',
    'E-mail' => '',
    'E-mail confirmed' => 'E-Mail 승인됨',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => '<b>{email}</b> 로 계정 활성화 링크를 보냈습니다. 이 메일은 {minutes}분 동안 유효합니다',
    'Edit' => '편집',
    'Editing' => '편집중',
    'Editing permission group' => '권한 그룹 편집중',
    'Editing permission: ' => '권한 편집중',
    'Editing role: ' => '역할 편집중',
    'Editing user: ' => '사용자 편집중',
    'For example: 123.34.56.78, 168.111.192.12' => '예시 : 123.34.56.78, 168.111.192.12',
    'Group' => '그룹',
    'ID' => '',
    'Inactive' => '비활성화',
    'IP' => '',
    'Language' => '언어',
    'Login' => '로그인',
    'Name' => '이름',
    'OS' => '운영체제',
    'Password' => '암호',
    'Password has been changed' => '암호가 변경 되었습니다',
    'Permission creation' => '권한 생성',
    'Permission groups' => '권한 그룹들',
    'Permissions' => '권한들',
    'Permissions for role:' => '역할을 위한 권한',
    'Refresh routes' => '',
    'Refresh routes (and delete unused)' => '',
    'Registration IP' => '등록 IP',
    'Repeat password' => '암호 반복',
    'Reset' => '재설정',
    'Role creation' => '역할 생성',
    'Roles' => '역할들',
    'Roles and permissions' => '역할과 권한',
    'Roles and permissions for user:' => '사용자를 위한역할과 권한:',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => '',
    'Rule' => '규칙',
    'Save' => '저장',
    'Saved' => '저장됨',
    'Search' => '검색',
    'Search route' => '',
    'Settings for permission' => '권한을 위한설정',
    'Show all' => '',
    'Show only selected' => '',
    'Status' => '상태',
    'Superadmin' => '슈퍼 관리자',
    'Token' => '',
    'Too many attempts' => '너무 많은 시도들',
    'Type' => '유형',
    'Updated' => '수정됨',
    'User' => '사용자',
    'User agent' => '사용자 에이전트',
    'User creation' => '사용자 생성',
    'Users' => '사용자들',
    'Visit Time' => '방문 시간',
    'Visit log' => '방문 로그',
    'Wrong format. Enter valid IPs separated by comma' => '잘못된 형식입니다. 정확한 아이피들을 콤마로 나눠 입력바랍니다',
    'Wrong password' => '잘못된 암호',
    'You can not change own permissions' => '당신에게 주어진 권한을 변경 할 수 없습니다',
];
