<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail' => '',
    'Username' => '사용자 이름',
    'Authorization' => '권한 부여',
    'Captcha' => '보안 문자',
    'Check your E-mail for further instructions' => '다음에 따라 이메일을 체크해주세요',
    'Check your e-mail {email} for instructions to activate account' => '계정을 활성화 하기위한 지침은 전자 메일 { 이메일을 확인 }',
    'Confirm' => '확인',
    'Confirm E-mail' => 'E-Mail 확인',
    'Continue' => '계속',
    'Could not send confirmation email' => '확인 이메일을 보낼 수 없습니다',
    'E-mail confirmation for' => 'E-Mail을 확인',
    'E-mail confirmed' => 'E-Mail 확인됨',
    'E-mail is invalid' => 'E-Mail이 부정확합니다',
    'Forgot password ?' => '암호를 잊으셨습니까?',
    'Incorrect username or password.' => '사용자 이름 또는 암호가 맞지 않습니다.',
    'Login' => '로그인',
    'Login has been taken' => '로그인이 되었습니다',
    'Password' => '암호',
    'Password recovery' => '암호 복구',
    'Password reset for' => '암호 재설정',
    'Recover' => '복구',
    'Register' => '등록',
    'Registration' => '등록중',
    'Registration - confirm your e-mail' => '등록 - 귀하의 E-mail 확인',
    'Remember me' => '현재 사용자를 기억',
    'Repeat password' => '암호 반복',
    'This E-mail already exists' => '이메일은 이미 존재합니다',
    'Token not found. It may be expired' => '토큰을 찾을 수 없습니다. 이것은 만료되었을 수 있습니다',
    'Token not found. It may be expired. Try reset password once more' => '토큰을 찾을 수 없습니다. 이것은 만료되었을 수 있습니다. 암호재설정을 한번 더 실행해 주세요.',
    'Too many attempts' => '너무 많은 시도를 했습니다',
    'Unable to send message for email provided' => '제출된 주소로 메일을 보낼수 없습니다',
    'You could not login from this IP' => '이 아이피로 로그인 할 수 없습니다',
];
